### ISSUE TITLE
spBlogger generates error

### ISSUE THREAD

**Issue by DuffDX** [spbooks/angularjs1#11]
I've downloaded the code and made the updates according to the book (Chapter 6) and I get this error: 
Uncaught Error: [$injector:modulerr] Failed to instantiate module spBlogger due to:
Error: [$injector:modulerr] Failed to instantiate module spBlogger.posts due to:
Error: [$injector:unpr] Unknown provider: $stateProvider
http://errors.angularjs.org/1.3.0-beta.2/$injector/unpr?p0=%24stateProvider
    at http://localhost:8000/lib/angular/angular.js:78:12
    at http://localhost:8000/lib/angular/angular.js:3596:19
    at getService (http://localhost:8000/lib/angular/angular.js:3723:39)
    at Object.invoke (http://localhost:8000/lib/angular/angular.js:3750:13)
    at http://localhost:8000/lib/angular/angular.js:3679:37
    at Array.forEach (native)
    at forEach (http://localhost:8000/lib/angular/angular.js:322:11)
    at loadModules (http://localhost:8000/lib/angular/angular.js:3666:5)
    at http://localhost:8000/lib/angular/angular.js:3673:40
    at Array.forEach (native)
http://errors.angularjs.org/1.3.0-beta.2/$injector/modulerr?p0=spBlogger.po…ngular%2Fangular.js%3A3673%3A40%0A%20%20%20%20at%20Array.forEach%20(native)
    at http://localhost:8000/lib/angular/angular.js:78:12
    at http://localhost:8000/lib/angular/angular.js:3700:15
    at Array.forEach (native)
    at forEach (http://localhost:8000/lib/angular/angular.js:322:11)
    at loadModules (http://localhost:8000/lib/angular/angular.js:3666:5)
    at http://localhost:8000/lib/angular/angular.js:3673:40
    at Array.forEach (native)
    at forEach (http://localhost:8000/lib/angular/angular.js:322:11)
    at loadModules (http://localhost:8000/lib/angular/angular.js:3666:5)
    at createInjector (http://localhost:8000/lib/angular/angular.js:3606:11)

$stateProvider is set in app/modules/postModule.js
Can somebody help me figure out where I went off the rails?

**Comment by frogfood** [comment]
I have the same exact error.  I had to add ui.router to app.js:

angular.module('spBlogger',['ui.router','spBlogger.posts','spBlogger.controllers','spBlogger.directives','spBlogger.filters','spBlogger.services']);

**Comment by DuffDX** [comment]
frogfood, I've figured it out. There are a couple of issues that need to be addressed.

First, in **app/modules/postModule.js**, you need to add 'ui.router' to the array, after 'spBlogger.posts.filters'

Then, in **app.js** the code provided in the book is in error. Sandpeep provides this code to add to app.js:

```
angular.module('spBlogger').run(['state , function(state){ $state.go('allPosts'); }]);
```

However, this is improperly formatted and is missing the $ in the name. It should be this:

```
angular.module('spBlogger').run(['$state' , function($state){ $state.go('allPosts'); }]);
```

Fixing those two issues has it running for me.

**Comment by frogfood** [comment]
That worked for me too, thank you!

**Comment by DuffDX** [comment]
Sandpeep - you might want to update the text in your e-book to correct the error.
