### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by jbonigomes** [spbooks/angularjs1#2]
Hi there, great book, however, I am not being able to run the last set of unit tests from page 124, in the PostDetailsController test, the 'it' part of the test injects $state and $stateParams, for some reason, the $stateParam can be injected correctly, however, the $state cannot, I triple checked and angular ui is present in my karma.conf and in my beforeEach()

http://cl.ly/image/1i0u3w2m1Z21

**Comment by panda-sandeep** [comment]
I will look into this and get back to you. Thanks for reporting.

**Comment by jbonigomes** [comment]
Thanks

**Comment by jbonigomes** [comment]
Closing this issue, I figured this out, bower was using a different version from what the app requires
