### ISSUE TITLE
Broken link for the The Angular Seed Project

### ISSUE THREAD

**Issue by sennamohan** [spbooks/angularjs1#20]
"https://github.com/angular/angularseed/
tree/69c9416c8407fd5806aab3c63916dfcf0522ecbc"

This link, given in the book is giving 404 error. Please give some advice how we can get this.

**Comment by simonmackie** [comment]
Hi @sennamohan, you have the wrong URL. please try https://github.com/angular/angular-seed/tree/69c9416c8407fd5806aab3c63916dfcf0522ecbc (I just checked my copy of the book, and that's the URL in the book)

**Comment by sennamohan** [comment]
Hi,

Thanks. Now I have got the zip down loaded. Appreciate your prompt help.
