### ISSUE TITLE
Unauthorized (API Calls to rhcloud)

### ISSUE THREAD

**Issue by jbonigomes** [spbooks/angularjs1#3]
I have been playing with the exercises from chapter 9, I get read and update data in the rhcloud spBlogger API, but I can't seem to be allowed to delete or create new entries, am I doing something wrong? Or is the API protected against delete and post verbs?

**Comment by panda-sandeep** [comment]
Hi there,

Any error message in the console? A screenshot will be helpful.

To make POST and DELETE requests you need to login first. Are you sure you have logged into the app (using admin/admin)? 

Also the rhcloud app accepts connections only from localhost:8000 (done using access-control-allow-origin header). So make sure you have not changed the port to something else.

**Comment by jbonigomes** [comment]
I think you solved the problem, I am not logged in, I have not yet arrived at the auth part of the app, so will only be able to login later, will close this issue, thanks Sandeep
