### ISSUE TITLE
Cross-Origin XMLHttpRequest

### ISSUE THREAD

**Issue by jifffffy** [spbooks/angularjs1#8]
hi 
when I type node ../scripts/web-server.js . the console show:
 " GET http://spblogger-sitepointdemos.rhcloud.com/api/posts  (index):1
 XMLHttpRequest cannot load http://spblogger-sitepointdemos.rhcloud.com/api/posts. No 'Access-Control-Allow-Origin' header is present on the requested resource. 
how can I do ?

**Comment by panda-sandeep** [comment]
Is your application running on any port other than 8000? Your app should be accessible from http://localhost:8000 .
